import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import LoginLogout from "~/components/LoginLogout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Shapes Mag</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
        <h1 className="text-3xl font-bold tracking-tight text-white sm:text-[5rem]">
          <div className="max-h-[400px] max-w-[400px]">
            <Image
              alt="shapeslogo"
              src={"/shapeslogo.PNG"}
              className="aspect-auto h-full w-full"
            />
          </div>
          ShapesMag
        </h1>
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
          <Link
            className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
            href="/battlestats"
          >
            <h3 className="text-2xl font-bold">BattleStats →</h3>
            <div className="text-lg">
              Full Breakdown of the Stats from every ShapesMag Event!
            </div>
          </Link>
          <Link
            className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
            href="/athletes"
          >
            <h3 className="text-2xl font-bold">Athletes →</h3>
            <div className="text-lg">
              Detailed information about Athlete&apos;s past performance
            </div>
          </Link>
          <LoginLogout />
        </div>
      </div>
    </>
  );
};

export default Home;
